# Exclude a variety of commonly ignored directories.
extend-exclude = ["venv", "docs/conf.py"]
# Same as Black.
line-length = 99
# Assume Python 3.9.
target-version = "py39"
# Enable using ruff with notebooks
extend-include = ["*.ipynb"]

[lint]
select = [
  "E",   # pycodestyle
  "W",   # pycodestyle
  "C",   # mccabe
  "F",   # pyflakes
  "UP",  # pyupgrade
  "N",   # pep8-naming
  "YTT", # flake8-2020
  "BLE", # flake8-blind-except
  "B",   # flake8-bugbear
  "C4",  # flake8-comprehensions
  "T10", # flake8-debugger
  "FA",  # flake8-future-annotations
  "EM",  # flake8-errmsg
  "I",   # isort (activates import sorting for formatter)
  "ISC", # flake8-implicit-str-concat
  "PIE", # flake8-pie
  "PT",  # flake8-pytest-style
  "RSE", # flake8-raise
  "RET", # flake8-return
  "SIM", # flake8-simplify
  "TCH", # flake8-type-checking
  "ARG", # flake8-unused-arguments
  "PTH", # flake8-use-pathlib
  "ERA", # eradicate
  "PD",  # pandas-vet
  "PGH", # pygrep-hooks
  "RUF", # Ruff-specific
]

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[lint.per-file-ignores]
"tests/*" = ["ARG001"]

[lint.isort]
required-imports = ["from __future__ import annotations"]
known-first-party = ["pyglotaran_extras"]
force-single-line = true

[lint.pydocstyle]
convention = "numpy"
